
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册账户</title>
</head>
<body>
<form action="/er/register" method="post">
    <input type="text" name="name" placeholder="姓名" required="required"/>
    <input type="text" name="idCard" placeholder="身份证号码" required="required"/>
    <input type="text" name="phoneNum" placeholder="手机号" required="required"/>
    <input type="text" name="nickname" placeholder="微信用户名" required="required"/>
    <input type="text" name="avatar" placeholder="微信头像" required="required"/>
    <input type="text" name="address" placeholder="地址" required="required"/>
    <button type="submit">登录</button>
</form>
</body>
</html>